### ISSUE TITLE
Support multiplatform build

### ISSUE THREAD

**Issue by nutgaard** [timo-reymann/dockerhub-semantic-release-gh-action#3]
### Description

It would be nice if we could pass `platforms` as an option to this action in order to publish images for multiple architectures. E.g linux/amd64,linux/arm64

From what I can understand this is supported in `docker/build-push-action@v5`;
```yaml
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: user/app:latest
```

If this is something that seems intereresting let me know, and I'll look into creating a PR.
